### ISSUE TITLE
Doesn't work with Openfl 9.2.0 and Lime 8

### ISSUE THREAD

**Issue by flashultra** [TerryCavanagh/hx_arabic_shaper#1]
I follow the instructions, but the `shaped` and `bidi` vars return empty string. After the init method I call ```print('سعر المنتج ١٥٠ ر' + 'يال' );```  for HTML5 target.

**Comment by TerryCavanagh** [comment]
Hey, thanks! We'll look into this.

What version of Haxe are you using?

**Comment by flashultra** [comment]
Haxe  4.2.3 , but I can try with the latest 4.2.5

**Comment by TerryCavanagh** [comment]
This was made with 3.x.x, so that's more likely to work! If you try that, let me know if that works.

**Comment by flashultra** [comment]
I just updated to 4.2.5 and did a test. The result is the same - empty values.

**Comment by flashultra** [comment]
I use too many features of 4.x.x. and 3.x.x won't work for me. I could make a test only to check if it works or not

**Comment by TerryCavanagh** [comment]
Ok! I did some testing, and can confirm this isn't working correctly in HTML5 builds. In haxe 3.x the shaper isn't working, in haxe 4.x it returns an empty string. 

Fixing this is a bit beyond me, but I'll ping Justo and ask him to take a look when he next has some time.

(more details below, which might be useful for future reference:)

I made a simple sample project in Haxegon. Here it is for reference: [arabic_hx_test.zip](https://github.com/TerryCavanagh/hx_arabic_shaper/files/9579270/arabic_hx_test.zip). It displays the string `مرحبا بالعالم`.

**Using haxe 3.4.4, openfl 9.2.0, lime 8.0.0, `windows` build:**
![image](https://user-images.githubusercontent.com/2874150/190516493-f594fb38-af00-44e3-8dfd-da45b613a209.png)
Works as intended.

**Using haxe 3.4.4, openfl 9.2.0, lime 8.0.0, `html5` build:**
![image](https://user-images.githubusercontent.com/2874150/190515419-de52c82e-b14e-4794-af8e-859a1ca1f0ce.png)
This is incorrect, but it's displaying something at least.

**Using haxe 4.2.5, openfl 9.2.0, lime 8.0.0, `html5` build:**
![image](https://user-images.githubusercontent.com/2874150/190517420-2205d738-8a9c-4ad2-8824-1a40e250631f.png)
This is displaying nothing.

(did you try a windows build with haxe 4.x? Did that work?)

**Comment by flashultra** [comment]
Yes, I tried the Windows build and the textfield is empty too.

**Comment by TerryCavanagh** [comment]
Just tried a windows build with Openfl 9.2/Lime 8.0 with Haxe 4, and that is also displaying nothing:

![image](https://user-images.githubusercontent.com/2874150/190580762-42a20930-6c55-4665-91ab-71d00526b28f.png)

So, there are two separate bugs here, which I'll create issues for

**Comment by mrcdk** [comment]
Hi! There's no need to use this library if you are using it with openfl/lime and targeting HTML5 because openfl/lime uses the web platform to render the text and it already do the shaping.

**Comment by flashultra** [comment]
I tried the latest patch (with a simple openfl project) targeting hxcpp ( windows target), but the text is still not visible .
Here is the full source code for test ( using oswald.ttf font ) . bidi return empty string  ( openfl 9.2.0 , haxe 4.2.5)
```haxe
import openfl.Assets;
import openfl.text.TextFormat;
import openfl.text.TextField;
import openfl.events.Event;
import openfl.display.Sprite;
import hx_arabic_shaper.ArabicReshaper;
import hx_arabic_shaper.bidi.UBA;

class Main extends Sprite {
	public function new() {
		super();
		addEventListener(Event.ADDED_TO_STAGE, onAddedToStage);
	}
	
	private function onAddedToStage(event:Event):Void {
		removeEventListener(Event.ADDED_TO_STAGE, onAddedToStage);
		init();
	}

  function init(){
		var config = ArabicReshaper.getDefaultConfig();
		config.delete_harakat = true;
		ArabicReshaper.init(config);
		var shaped = ArabicReshaper.reshape("مرحبا بالعالم");
		var bidi = UBA.display(shaped);
		trace("Bidi: "+bidi);  // it's empty
		var myTextField:TextField = new TextField();
		addChild(myTextField);
                // fontname = Oswald Regular
		myTextField.defaultTextFormat = new TextFormat(Assets.getFont("data/fonts/oswald.ttf").fontName, 32, 0xE80F0F);
		myTextField.text = bidi;
		myTextField.x = 100;
		myTextField.y = 100;
		myTextField.width = 300;
  }
}
```

**Comment by TerryCavanagh** [comment]
Hey -

I think this is just the font you're using - your example works fine for me when I use the Arabic Noto Sans font instead of Oswald Regular (Which doesn't have the arabic characters):

![image](https://user-images.githubusercontent.com/2874150/204653898-154953b2-1db9-4455-bcd6-06d90cb8b2bc.png)

i.e.:

```
 // fontname = Noto Sans Arabic Regular
		myTextField.defaultTextFormat = new TextFormat(Assets.getFont("data/fonts/notosansarabicregular.ttf").fontName, 32, 0xE80F0F);
```

This bit is weird though:
>trace("Bidi: "+bidi);  // it's empty

**Comment by flashultra** [comment]
Maybe I did some modification to Lime from before when I was doing a test with Arabic. I'll try a clean install of Lime. Thank you!

**Comment by TerryCavanagh** [comment]
No worries, let me know how you get on with it!
