### ISSUE TITLE
Shaper returns blank strings with Haxe 4.2.5

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/hx_arabic_shaper#2]
see https://github.com/TerryCavanagh/hx_arabic_shaper/issues/1

Using haxe 4.2.5, openfl 9.2.0, lime 8.0.0, simple example project: https://github.com/TerryCavanagh/hx_arabic_shaper/files/9579270/arabic_hx_test.zip

**Comment by mrcdk** [comment]
This should be fixed now here https://github.com/TerryCavanagh/hx_arabic_shaper/commit/756de324ef65d2c24d3391a5d1336c583881b7ef
