### ISSUE TITLE
Shaper doesn't return correct result in HTML5

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/hx_arabic_shaper#3]
Tested with both Haxe 3.4.4 and Haxe 4.2.5. See https://github.com/TerryCavanagh/hx_arabic_shaper/issues/1

Expected result:

![image](https://user-images.githubusercontent.com/2874150/190516493-f594fb38-af00-44e3-8dfd-da45b613a209.png)

HTML5 result:

![image](https://user-images.githubusercontent.com/2874150/190515419-de52c82e-b14e-4794-af8e-859a1ca1f0ce.png)

This is using haxe 3.4.4, openfl 9.2.0, lime 8.0.0, html5 build. Haxe 4.2.5 displays nothing. 

Simple example project: https://github.com/TerryCavanagh/hx_arabic_shaper/files/9579270/arabic_hx_test.zip

**Comment by mrcdk** [comment]
There's no need to use this library if you are using it with openfl/lime and targeting HTML5 because openfl/lime uses the web platform to render the text and it already do the shaping!
